/**
 * Credential proxy for container isolation.
 * Containers connect here instead of directly to the Anthropic API.
 * The proxy injects real credentials so containers never see them.
 *
 * Two auth modes:
 *   API key:  Proxy injects x-api-key on every request.
 *   OAuth:    Container CLI exchanges its placeholder token for a temp
 *             API key via /api/oauth/claude_cli/create_api_key.
 *             Proxy injects real OAuth token on that exchange request;
 *             subsequent requests carry the temp key which is valid as-is.
 *
 * Uses curl as the HTTP transport for upstream requests to avoid Cloudflare
 * TLS fingerprint blocking (Node.js JA3 fingerprint gets flagged by WAFs).
 *
 * Retries transient upstream failures (500/502/503/529, connection errors)
 * with exponential backoff before returning an error to the container.
 *
 * When Cloudflare WAF blocks a request (403 with HTML body), the proxy
 * progressively trims old messages from the request body and retries.
 * This handles cases where conversation history contains shell commands
 * that Cloudflare's WAF misidentifies as command injection attacks.
 */
import { createServer, IncomingMessage, Server, ServerResponse } from 'http';
import { spawn } from 'child_process';
import { writeFileSync, unlinkSync } from 'fs';

import { readEnvFile } from './env.js';
import { logger } from './logger.js';

export type AuthMode = 'api-key' | 'oauth';

export interface ProxyConfig {
  authMode: AuthMode;
}

const MAX_RETRIES = 3;
const RETRY_BASE_MS = 2000;
const RETRYABLE_STATUS = new Set([500, 502, 503, 529]);

function isCloudflareBlock(statusCode: number, body: Buffer): boolean {
  if (statusCode !== 403) return false;
  const text = body.toString('utf-8', 0, Math.min(body.length, 200));
  return text.includes('<!DOCTYPE html') || text.includes('cloudflare');
}

function isThinkingSignatureError(statusCode: number, body: Buffer): boolean {
  if (statusCode !== 400) return false;
  const text = body.toString('utf-8', 0, Math.min(body.length, 1000));
  return text.includes('Invalid signature') && text.includes('thinking');
}

/**
 * Strip thinking blocks from assistant messages in conversation history.
 * Bedrock/GMI backends validate thinking block signatures, but signatures
 * generated by one provider may be rejected by another. Stripping thinking
 * blocks is safe — the model loses access to prior chain-of-thought but
 * the conversation continues normally.
 */
function stripThinkingBlocks(data: Record<string, unknown>): boolean {
  const msgs = data.messages as Array<{ role: string; content: unknown }>;
  if (!msgs || !Array.isArray(msgs)) return false;

  let modified = false;
  for (const msg of msgs) {
    if (msg.role !== 'assistant' || !Array.isArray(msg.content)) continue;
    const before = (msg.content as Array<{ type: string }>).length;
    msg.content = (msg.content as Array<{ type: string }>).filter(
      (block) => block.type !== 'thinking',
    );
    if ((msg.content as unknown[]).length !== before) modified = true;
  }
  return modified;
}

/**
 * Sanitize request body to bypass Cloudflare WAF.
 * Cloudflare's WAF detects shell command patterns (nslookup, curl, cat /etc/passwd, etc.)
 * inside JSON string values and blocks them as command injection.
 * This happens because conversation history contains Bash tool_use blocks with real commands
 * and tool_result blocks with shell output.
 *
 * Strategy: redact Bash commands and tool results from all messages except the last
 * user turn, preserving message structure so the API still works.
 */
function sanitizeBodyForWAF(body: Buffer): Buffer | null {
  try {
    const data = JSON.parse(body.toString());
    if (!data.messages || !Array.isArray(data.messages)) return null;

    let modified = false;
    const msgs = data.messages;

    // Collect tool_use IDs for Bash tools so we can redact their results too
    const bashToolIds = new Set<string>();

    for (const msg of msgs) {
      const content = msg.content;
      if (!Array.isArray(content)) continue;

      for (const block of content) {
        if (block.type === 'tool_use' && block.name === 'Bash') {
          bashToolIds.add(block.id);
          if (block.input?.command) {
            block.input.command = '[redacted by proxy]';
            modified = true;
          }
        }
      }
    }

    // Redact tool_result content for Bash tools
    for (const msg of msgs) {
      const content = msg.content;
      if (!Array.isArray(content)) continue;

      for (const block of content) {
        if (
          block.type === 'tool_result' &&
          bashToolIds.has(block.tool_use_id)
        ) {
          if (typeof block.content === 'string' && block.content.length > 0) {
            block.content = '[output redacted by proxy]';
            modified = true;
          } else if (Array.isArray(block.content)) {
            block.content = '[output redacted by proxy]';
            modified = true;
          }
        }
      }
    }

    return modified ? Buffer.from(JSON.stringify(data)) : null;
  } catch {
    return null;
  }
}

export function startCredentialProxy(
  port: number,
  host = '127.0.0.1',
): Promise<Server> {
  const secrets = readEnvFile([
    'ANTHROPIC_API_KEY',
    'CLAUDE_CODE_OAUTH_TOKEN',
    'ANTHROPIC_AUTH_TOKEN',
    'ANTHROPIC_BASE_URL',
  ]);

  const authMode: AuthMode = secrets.ANTHROPIC_API_KEY ? 'api-key' : 'oauth';
  const oauthToken =
    secrets.CLAUDE_CODE_OAUTH_TOKEN || secrets.ANTHROPIC_AUTH_TOKEN;

  const upstreamBase =
    secrets.ANTHROPIC_BASE_URL || 'https://api.anthropic.com';

  // Only forward headers the API actually needs; drop everything else
  // to avoid triggering Cloudflare WAF on third-party providers.
  const ALLOWED_HEADERS = new Set([
    'content-type',
    'anthropic-version',
    'anthropic-beta',
    'accept',
  ]);

  function buildCurlHeaders(req: IncomingMessage): Record<string, string> {
    const headers: Record<string, string> = {};

    for (const [key, value] of Object.entries(req.headers)) {
      if (!value) continue;
      if (!ALLOWED_HEADERS.has(key.toLowerCase())) continue;
      headers[key] = Array.isArray(value) ? value.join(', ') : value;
    }

    // Force identity encoding so we never get compressed error pages
    headers['accept-encoding'] = 'identity';

    if (authMode === 'api-key') {
      headers['x-api-key'] = secrets.ANTHROPIC_API_KEY;
    } else if (oauthToken) {
      headers['authorization'] = `Bearer ${oauthToken}`;
    }

    return headers;
  }

  let bodyFileCounter = 0;

  function doCurlRequest(
    req: IncomingMessage,
    body: Buffer,
    headers: Record<string, string>,
  ): Promise<{
    statusCode: number;
    responseHeaders: Record<string, string>;
    responseBody: Buffer;
  }> {
    return new Promise(async (resolve, reject) => {
      const url = `${upstreamBase}${req.url}`;

      // Write body to a temp file so curl knows the Content-Length upfront
      // (piping via stdin causes chunked transfer which some WAFs reject)
      const bodyFile = `/tmp/proxy-req-${process.pid}-${bodyFileCounter++}.bin`;
      const fs = await import('fs');
      try {
        fs.writeFileSync(bodyFile, body);
      } catch (err) {
        reject(new Error(`Failed to write body file: ${err}`));
        return;
      }

      const args: string[] = [
        '-s',
        '-4', // force IPv4 to avoid Cloudflare IPv6 issues
        '-X',
        req.method || 'POST',
        '-D',
        '/dev/stderr',
        '--max-time',
        '300',
      ];

      for (const [key, value] of Object.entries(headers)) {
        args.push('-H', `${key}: ${value}`);
      }

      args.push('--data-binary', `@${bodyFile}`);
      args.push(url);

      const proc = spawn('curl', args, { stdio: ['pipe', 'pipe', 'pipe'] });

      const stdoutChunks: Buffer[] = [];
      const stderrChunks: Buffer[] = [];

      proc.stdout.on('data', (c) => stdoutChunks.push(c));
      proc.stderr.on('data', (c) => stderrChunks.push(c));

      proc.on('error', (err) => {
        try {
          fs.unlinkSync(bodyFile);
        } catch {
          /* ignore */
        }
        reject(err);
      });
      proc.on('close', (code) => {
        try {
          fs.unlinkSync(bodyFile);
        } catch {
          /* ignore */
        }

        if (code !== 0 && stdoutChunks.length === 0) {
          reject(new Error(`curl exited with code ${code}`));
          return;
        }

        const responseBody = Buffer.concat(stdoutChunks);
        const headerText = Buffer.concat(stderrChunks).toString();

        let statusCode = 200;
        const responseHeaders: Record<string, string> = {};

        for (const line of headerText.split('\r\n')) {
          if (line.startsWith('HTTP/')) {
            const match = line.match(/HTTP\/[\d.]+ (\d+)/);
            if (match) statusCode = parseInt(match[1], 10);
          } else if (line.includes(':')) {
            const idx = line.indexOf(':');
            const key = line.slice(0, idx).trim().toLowerCase();
            const value = line.slice(idx + 1).trim();
            if (key && value) responseHeaders[key] = value;
          }
        }

        resolve({ statusCode, responseHeaders, responseBody });
      });
    });
  }

  async function sendWithRetries(
    req: IncomingMessage,
    body: Buffer,
    headers: Record<string, string>,
  ): Promise<{
    statusCode: number;
    responseHeaders: Record<string, string>;
    responseBody: Buffer;
  } | null> {
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        const result = await doCurlRequest(req, body, headers);

        if (result.statusCode >= 400) {
          logger.warn(
            {
              method: req.method,
              url: req.url,
              status: result.statusCode,
              body: result.responseBody.toString().slice(0, 200),
            },
            'Upstream error response',
          );
        }

        const shouldRetry =
          RETRYABLE_STATUS.has(result.statusCode) ||
          isCloudflareBlock(result.statusCode, result.responseBody);

        if (shouldRetry && attempt < MAX_RETRIES) {
          const delay = RETRY_BASE_MS * Math.pow(2, attempt);
          logger.warn(
            {
              url: req.url,
              status: result.statusCode,
              attempt: attempt + 1,
              delay,
            },
            'Retryable upstream error, backing off',
          );
          await new Promise((r) => setTimeout(r, delay));
          continue;
        }

        return result;
      } catch (err) {
        if (attempt < MAX_RETRIES) {
          const delay = RETRY_BASE_MS * Math.pow(2, attempt);
          logger.warn(
            { err, url: req.url, attempt: attempt + 1, delay },
            'Upstream connection error, retrying',
          );
          await new Promise((r) => setTimeout(r, delay));
          continue;
        }
        throw err;
      }
    }
    return null;
  }

  async function handleRequest(
    req: IncomingMessage,
    res: ServerResponse,
    body: Buffer,
  ): Promise<void> {
    const headers = buildCurlHeaders(req);

    logger.info(
      { method: req.method, url: req.url, bodyLen: body.length },
      'Proxy request',
    );

    try {
      let result = await sendWithRetries(req, body, headers);

      // If Bedrock rejected thinking block signatures (400 + "Invalid signature"),
      // strip thinking blocks and retry. This preserves thinking context for
      // providers that accept it, and only degrades when necessary.
      if (
        result &&
        isThinkingSignatureError(result.statusCode, result.responseBody)
      ) {
        try {
          const data = JSON.parse(body.toString());
          if (stripThinkingBlocks(data)) {
            const stripped = Buffer.from(JSON.stringify(data));
            logger.info(
              { originalSize: body.length, strippedSize: stripped.length },
              'Retrying with thinking blocks stripped (invalid signature)',
            );
            result = await sendWithRetries(req, stripped, headers);
          }
        } catch {
          /* parse failure — can't strip, return original error */
        }
      }

      // If Cloudflare WAF blocked the request (body content triggers WAF rules
      // e.g. shell commands in conversation history), sanitize and retry
      const bodyForWAF = body;
      if (result && isCloudflareBlock(result.statusCode, result.responseBody)) {
        const sanitized = sanitizeBodyForWAF(bodyForWAF);
        if (sanitized) {
          logger.info(
            { originalSize: body.length, sanitizedSize: sanitized.length },
            'Retrying with sanitized body to bypass Cloudflare WAF',
          );
          result = await sendWithRetries(req, sanitized, headers);
        }
      }

      if (!result) {
        if (!res.headersSent) {
          res.writeHead(502);
          res.end('Bad Gateway');
        }
        return;
      }

      const fwdHeaders: Record<string, string> = {};
      for (const key of [
        'content-type',
        'x-request-id',
        'request-id',
        'anthropic-ratelimit-requests-limit',
        'anthropic-ratelimit-requests-remaining',
        'anthropic-ratelimit-tokens-limit',
        'anthropic-ratelimit-tokens-remaining',
        'retry-after',
      ]) {
        if (result.responseHeaders[key])
          fwdHeaders[key] = result.responseHeaders[key];
      }

      res.writeHead(result.statusCode, fwdHeaders);
      res.end(result.responseBody);
    } catch (err) {
      logger.error(
        { err, url: req.url },
        'Credential proxy upstream error (retries exhausted)',
      );
      if (!res.headersSent) {
        res.writeHead(502);
        res.end('Bad Gateway');
      }
    }
  }

  return new Promise((resolve, reject) => {
    const server = createServer((req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (c) => chunks.push(c));
      req.on('end', () => {
        const body = Buffer.concat(chunks);
        handleRequest(req, res, body).catch((err) => {
          logger.error({ err }, 'Unexpected proxy handler error');
          if (!res.headersSent) {
            res.writeHead(500);
            res.end('Internal Server Error');
          }
        });
      });
    });

    server.listen(port, host, () => {
      logger.info({ port, host, authMode }, 'Credential proxy started');
      resolve(server);
    });

    server.on('error', reject);
  });
}

/** Detect which auth mode the host is configured for. */
export function detectAuthMode(): AuthMode {
  const secrets = readEnvFile(['ANTHROPIC_API_KEY']);
  return secrets.ANTHROPIC_API_KEY ? 'api-key' : 'oauth';
}
